name: fminimal
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  cloud_firestore: ^3.1.11
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true